import { useState } from "react";
import { api } from "../api";
import { ErrorBanner } from "./ui";

// On-demand, advisory LLM suggestion. The deterministic recommendation stays
// authoritative; this panel says whether the LLM agrees and why.
export default function SuggestionPanel({ decisionId, asOf, onApply }) {
  const [state, setState] = useState({ status: "idle" });

  async function request() {
    setState({ status: "loading" });
    try {
      setState({ status: "done", data: await api.suggest(decisionId, asOf) });
    } catch (error) {
      setState({ status: "error", message: error.message });
    }
  }

  if (state.status === "idle" || state.status === "loading") {
    return (
      <div className="suggestion suggestion-idle">
        <div>
          <strong>AI suggestion</strong>
          <p className="muted small">Ask the LLM what to do, based on this decision's costs, deadline and recent changes.</p>
        </div>
        <button className="btn btn-outline btn-sm" onClick={request} disabled={state.status === "loading"}>
          {state.status === "loading" ? "Thinking…" : "Get suggestion"}
        </button>
      </div>
    );
  }

  if (state.status === "error") {
    return (
      <div className="suggestion">
        <ErrorBanner>{state.message}</ErrorBanner>
        <button className="btn btn-outline btn-sm" onClick={request}>Try again</button>
      </div>
    );
  }

  const s = state.data;
  return (
    <div className="suggestion">
      <div className="suggestion-head">
        <strong>AI suggestion</strong>
        <span className={`rec rec-${s.suggested_action}`}>{s.suggested_action}</span>
        <span className={`pill ${s.agrees_with_model ? "pill-ok" : "pill-warn"}`}>
          {s.agrees_with_model ? "Agrees with the calculated recommendation" : `Differs from calculated: ${s.model_recommendation}`}
        </span>
      </div>
      <p className="suggestion-headline">{s.headline}</p>
      <p>{s.rationale}</p>
      <div className="suggestion-cols">
        {s.risks.length > 0 && (
          <div>
            <h4>Risks</h4>
            <ul>{s.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul>
          </div>
        )}
        {s.next_steps.length > 0 && (
          <div>
            <h4>Next steps</h4>
            <ul>{s.next_steps.map((step) => <li key={step}>{step}</li>)}</ul>
          </div>
        )}
      </div>
      <p className="muted small">Advisory only, generated by an LLM from the figures above. The planner makes the final call.</p>
      <div className="btn-group">
        {onApply && (
          <button className="btn btn-primary btn-sm" onClick={() => onApply(s.suggested_action, s.headline)}>
            Apply “{s.suggested_action}”
          </button>
        )}
        <button className="btn btn-ghost btn-sm" onClick={request}>Regenerate</button>
      </div>
    </div>
  );
}
